name: sift
description: A lightweight map reading library that can be used in Dart and Flutter projects
version: 1.0.4
homepage: https://github.com/ShoutOutSoftware/Sift-Dart

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  intl: ^0.16.1

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
