name: sift
description: A lightweight map reading library that can be used in Dart and Flutter projects
version: 1.0.7
homepage: https://github.com/ShoutOutSoftware/Sift-Dart

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.1
  pedantic: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter