name: sift
description: A lightweight map reading library that can be used in Dart and Flutter projects
version: 1.0.15
homepage: https://github.com/ShoutOutSoftware/Sift-Dart

environment:
  sdk: ">=2.16.0 <3.19.4"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter